version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=example:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    container_name: producer
    restart: always
    build: ./producer
    environment:
      - KAFKA_HOST=kafka:9092
    ports:
      - "4000:4000"
    depends_on:
      - kafka
  consumer:
    container_name: consumer
    restart: always
    build: ./consumer
    ports:
      - "4001:4001"
    depends_on:
      - kafka
