version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_CREATE_TOPICS: "example:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  consumer:
    container_name: consumer
    restart: always
    build: ./consumer
    ports:
      - "4001:4001"
    depends_on:
      - kafka
  producer:
    container_name: producer
    restart: always
    build: ./producer
    ports:
      - "4000:4000"
    depends_on:
      - kafka      
